[package]
name = "sleep_rs"
version = "0.1.0"
edition = "2024"
authors = ["Stewart Chandler <stewartdchandler@gmail.com>"]
description = "A minimal sleep program built for windows."
readme = "README.md"

[[bin]]
name="sleep_rs"
test=false
bench=false

[dependencies]
windows-sys = { version = "0.61.2", default-features = false, features = ["Win32_System_Console", "Win32_System_Environment", "Win32_System_Threading"] }

[profile.dev]
panic="abort"

[profile.release]
panic="abort"
opt-level="z"
